/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.exalt.exalthexagonalarchikafkakeycloakbsmsnotificationservice.domain.events;
@org.apache.avro.specific.AvroGenerated
public enum State implements org.apache.avro.generic.GenericEnumSymbol<State> {
  ACTIVE, ARCHIVE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"State\",\"namespace\":\"com.exalt.exalthexagonalarchikafkakeycloakbsmsnotificationservice.domain.events\",\"symbols\":[\"ACTIVE\",\"ARCHIVE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
