
spring:
  application:
    name: ${CUSTOMER_APPLICATION_NAME}

  main:
    banner-mode: off

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOSTNAME}:${DATABASE_HOST_PORT}/${CUSTOMER_DATABASE}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: true
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  kafka:
    producer:
      bootstrap-servers: http://kafka-server1:19092,http://kafka-server2:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
    consumer:
      bootstrap-servers: http://kafka-server1:19092,http://kafka-server2:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific:
          avro:
            reader: true

    properties:
      schema:
        registry:
          url: http://schema-registry-service:8081
kafka:
  topic-config:
    name: ${KAFKA_TOPIC_NAME}
    retention:
      duration: ${KAFKA_TOPIC_RETENTION_DURATION} # one hour
      size: ${KAFKA_TOPIC_RETENTION_SIZE} # 0.5 MB
      clean-up-policy: ${KAFKA_TOPIC_RETENTION_CLEANUP_POLICY}
    topic-partitions: ${KAFKA_TOPIC_PARTITIONS}
    topic-replicas: ${KAFKA_TOPIC_REPLICAS}

server:
  port: ${CUSTOMER_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true # enable /actuator/health/liveness and /actuator/health/readiness for K8s
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_APPLICATION_NAME}:${SERVICE_REGISTRY_SERVER_PORT}/eureka/

