spring:
  application:
    name: exalt-hexagonal-archi-kafka-keycloak-gateway-service-proxy

  main:
    banner-mode: off

  cloud:
    gateway:
      route1:
        id: exalt-hexagonal-archi-kafka-keycloak-bs-ms-bank-account
        uri: http://localhost:8281
        predicate: /api/bank-account/**
      route2:
        id: exalt-hexagonal-archi-kafka-keycloak-bs-ms-customer
        uri: http://localhost:8282
        predicate: /api/customer/**
      route3:
        id: exalt-hexagonal-archi-kafka-keycloak-bs-ms-operation
        uri: http://localhost:8283
        predicate: /api/operation/**
      route4:
        id: exalt-hexagonal-archi-kafka-keycloak-bs-ms-notification-service
        uri: http://localhost:8284
        predicate: /api/notification/*

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true # enable /actuator/health/liveness and /actuator/health/readiness for K8s
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8280